name: C/C++ CI

on:
  push:
      branches: [ master ]
  pull_request:
      branches: [ master ]

jobs:
  build-and-test:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: install libcap
        run: sudo apt install -y libcap2 libcap-dev

      - name: build and install dependencies
        run: ./scripts/build-dependencies.sh

      - name: Run autoreconf
        run: autoreconf -i

      - name: Run configure
        run: ./configure

      - name: Run make
        run: make

      - name: Run make check
        if: always()
        run: |
          make check
          cat lib/*/test-suite.log
